import enum

class IncidentType(str, enum.Enum):
    MEDICAL = "MEDICAL"
    FIRE = "FIRE"
    ACCIDENT = "ACCIDENT"
    SECURITY = "SECURITY"
    THEFT = "THEFT"
    VIOLENCE = "VIOLENCE"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    ELECTRICAL = "ELECTRICAL"
    WATER = "WATER"
    TRANSPORT = "TRANSPORT"
    NATURAL_HAZARD = "NATURAL_HAZARD"
    MISSING_PERSON = "MISSING_PERSON"
    OTHER = "OTHER"

class IncidentStatus(str, enum.Enum):
    REPORTED = "REPORTED"
    ANALYZING = "ANALYZING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    DISPATCHING = "DISPATCHING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    IN_PROGRESS = "IN_PROGRESS"
    REPLANNING = "REPLANNING"
    RESOLVED = "RESOLVED"
    CANCELLED = "CANCELLED"

class Severity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class DepartmentName(str, enum.Enum):
    MEDICAL = "MEDICAL"
    SECURITY = "SECURITY"
    TRANSPORT = "TRANSPORT"
    FACILITIES = "FACILITIES"
    COMMUNICATION = "COMMUNICATION"
    NONE = "NONE"

class AssignmentStatus(str, enum.Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    DISPATCHED = "DISPATCHED"
    COMPLETED = "COMPLETED"

class NotificationType(str, enum.Enum):
    INCIDENT_RECEIVED = "INCIDENT_RECEIVED"
    DEPARTMENT_ASSIGNED = "DEPARTMENT_ASSIGNED"
    RESPONDER_ASSIGNED = "RESPONDER_ASSIGNED"
    RESPONDER_ACCEPTED = "RESPONDER_ACCEPTED"
    ETA_UPDATE = "ETA_UPDATE"
    REPLAN = "REPLAN"
    SAFETY_GUIDANCE = "SAFETY_GUIDANCE"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
